---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.name }}-ingress
  annotations:
    cert-manager.io/issuer: krogerissuer
    cert-manager.io/issuer-kind: KrogerIssuer
    cert-manager.io/issuer-group: certs.kroger.com
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "route"
    nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
    namespace: {{ .Values.namespace }}

spec:
  tls:
  - hosts:
      - {{ tpl .Values.ingress.hostTemplate . }}
    secretName: {{.Values.ingress.secret}}
  rules:
  - host: {{ tpl .Values.ingress.hostTemplate . }}   
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: svc-{{ .Values.name }}
            port:
              number: {{ .Values.servicePort }}
